tweak bin/compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -26,44 +26,49 @@ BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
 
-echo "-----> Detecting Racket version"
+# echo "-----> Detecting Racket version"
 
-RACKET_VERSION_PATH="$ENV_DIR/RACKET_VERSION"
+# RACKET_VERSION_PATH="$ENV_DIR/RACKET_VERSION"
 
-if [ ! -f "$RACKET_VERSION_PATH" ]; then
-  echo "     - ERROR: The RACKET_VERSION configuration variable does not appear to be set"
-  echo "     - Aborting..."
-  exit 1
-fi
+# if [ ! -f "$RACKET_VERSION_PATH" ]; then
+#   echo "     - ERROR: The RACKET_VERSION configuration variable does not appear to be set"
+#   echo "     - Aborting..."
+#   exit 1
+# fi
 
-RACKET_VERSION=$(cat "$RACKET_VERSION_PATH")
+# RACKET_VERSION=$(cat "$RACKET_VERSION_PATH")
 
-if [[ "$RACKET_VERSION" =~ '-minimal'$ ]]; then
-  RACKET_VERSION=${RACKET_VERSION%-minimal}
-  if [[ ${RACKET_VERSION,,} == 'current' || ${RACKET_VERSION,,} == 'head' ]]; then
-    echo "     - Using minimal Racket development snapshot"
-    RACKET_INSTALLER='http://www.cs.utah.edu/plt/snapshots/current/installers/min-racket-current-x86_64-linux-precise.sh'
-  else
-    echo "     - Using minimal Racket version $RACKET_VERSION"
-    if [[ "$RACKET_VERSION" =~ ^6.[0-4](\..+)?$ ]]; then
-      RACKET_INSTALLER="http://mirror.racket-lang.org/installers/${RACKET_VERSION}/racket-minimal-${RACKET_VERSION}-x86_64-linux-ubuntu-precise.sh"
-    else
-      RACKET_INSTALLER="http://mirror.racket-lang.org/installers/${RACKET_VERSION}/racket-minimal-${RACKET_VERSION}-x86_64-linux.sh"
-    fi
-  fi
-else
-  if [[ ${RACKET_VERSION,,} == 'current' || ${RACKET_VERSION,,} == 'head' ]]; then
-    echo "     - Using Racket development snapshot"
-    RACKET_INSTALLER='http://www.cs.utah.edu/plt/snapshots/current/installers/racket-current-x86_64-linux-precise.sh'
-  else
-    echo "     - Using Racket version $RACKET_VERSION"
-    if [[ "$RACKET_VERSION" =~ ^6.[0-4](\..+)?$ ]]; then
-      RACKET_INSTALLER="http://mirror.racket-lang.org/installers/${RACKET_VERSION}/racket-${RACKET_VERSION}-x86_64-linux-ubuntu-precise.sh"
-    else
-      RACKET_INSTALLER="http://mirror.racket-lang.org/installers/${RACKET_VERSION}/racket-${RACKET_VERSION}-x86_64-linux.sh"
-    fi
-  fi
-fi
+# if [[ "$RACKET_VERSION" =~ '-minimal'$ ]]; then
+#   RACKET_VERSION=${RACKET_VERSION%-minimal}
+#   if [[ ${RACKET_VERSION,,} == 'current' || ${RACKET_VERSION,,} == 'head' ]]; then
+#     echo "     - Using minimal Racket development snapshot"
+#     RACKET_INSTALLER='http://www.cs.utah.edu/plt/snapshots/current/installers/min-racket-current-x86_64-linux-precise.sh'
+#   else
+#     echo "     - Using minimal Racket version $RACKET_VERSION"
+#     if [[ "$RACKET_VERSION" =~ ^6.[0-4](\..+)?$ ]]; then
+#       RACKET_INSTALLER="http://mirror.racket-lang.org/installers/${RACKET_VERSION}/racket-minimal-${RACKET_VERSION}-x86_64-linux-ubuntu-precise.sh"
+#     else
+#       RACKET_INSTALLER="http://mirror.racket-lang.org/installers/${RACKET_VERSION}/racket-minimal-${RACKET_VERSION}-x86_64-linux.sh"
+#     fi
+#   fi
+# else
+#   if [[ ${RACKET_VERSION,,} == 'current' || ${RACKET_VERSION,,} == 'head' ]]; then
+#     echo "     - Using Racket development snapshot"
+#     RACKET_INSTALLER='http://www.cs.utah.edu/plt/snapshots/current/installers/racket-current-x86_64-linux-precise.sh'
+#   else
+#     echo "     - Using Racket version $RACKET_VERSION"
+#     if [[ "$RACKET_VERSION" =~ ^6.[0-4](\..+)?$ ]]; then
+#       RACKET_INSTALLER="http://mirror.racket-lang.org/installers/${RACKET_VERSION}/racket-${RACKET_VERSION}-x86_64-linux-ubuntu-precise.sh"
+#     else
+#       RACKET_INSTALLER="http://mirror.racket-lang.org/installers/${RACKET_VERSION}/racket-${RACKET_VERSION}-x86_64-linux.sh"
+#     fi
+#   fi
+# fi
+
+echo "-----> This is completely pre-alpha software "
+echo "-----> Using full racket installation "
+
+RACKET_INSTALLER="https://download.racket-lang.org/installers/8.6/racket-8.6-x86_64-linux-cs.sh"
 
 APP_DIR=$BUILD_DIR/app
 RACKET_DIR=$BUILD_DIR/racket
